version: '3.7'

services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=valore
    volumes:
      - ./data:/app/data